Let gh action continue on error

diff --git a/.github/workflows/plan-on-pr.yaml b/.github/workflows/plan-on-pr.yaml
--- a/.github/workflows/plan-on-pr.yaml
+++ b/.github/workflows/plan-on-pr.yaml
@@ -33,10 +33,13 @@ jobs:
           #terraform init #TODO
           exit 123
         working-directory: ./terraform
+        continue-on-error: true
 
       - run: |
           #TODO
           echo "$PR_NUMBER"
+          echo "tf-init failed"
+          exit 1
         if: ${{ steps.tf-init.outcome == 'failure' }}
         env:
           PR_NUMBER: ${{ github.event.number }}
